# Generated by Django 3.2.19 on 2023-05-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id_estadistica', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_estadistica', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LeyendaCompuesta',
            fields=[
                ('id_leyenda', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('leyenda_general', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadistica',
            fields=[
                ('id_tipo_estadistica', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nom_tipo_estadistica', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSerie',
            fields=[
                ('id_tipo_serie', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_serie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SerieDatos',
            fields=[
                ('id_serie', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_serie', models.CharField(max_length=100)),
                ('id_estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadistica')),
                ('id_tipo_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposerie')),
            ],
        ),
        migrations.AddField(
            model_name='estadistica',
            name='id_tipo_estadistica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoestadistica'),
        ),
        migrations.CreateModel(
            name='DatosSerie',
            fields=[
                ('id_dato', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('cantidad_dato', models.IntegerField()),
                ('leyenda_dato', models.CharField(max_length=50)),
                ('id_leyenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leyendacompuesta')),
                ('id_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seriedatos')),
            ],
        ),
    ]
