# Generated by Django 3.2.19 on 2023-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosserie',
            name='id_dato',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='id_estadistica',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leyendacompuesta',
            name='id_leyenda',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seriedatos',
            name='id_serie',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoestadistica',
            name='id_tipo_estadistica',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposerie',
            name='id_tipo_serie',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
